## ADM HOMEWORK 1

## Problem 1

## Introduction

### Say "Hello, World!" With Python

In [3]:
my_name=('Hello, World!')
print(my_name)

Hello, World!


### Python If-Else

In [4]:
#!/bin/python

import math
import os
import random
import re
import sys

n = int(input())
if n%2==1:
    print('Weird')
if n%2==0 and 2<=n<=5:
    print('Not Weird')
if n%2==0 and 6<=n<=20:
    print('Weird')
if n%2==0 and n>20:
    print('Not Weird')

 3


Weird


## Arithmetic Operators

In [7]:
a = int(input())                         
b = int(input())

if 1<=a<=10**10 and 1<=b<=10**10:        

 print (a+b)                             
 print (a-b)                      
 print (a*b)      


 3
 2


5
1
6


## Python: Division

In [8]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a//b)
    print(a/b)


 4
 3


1
1.3333333333333333


## Loops

In [9]:
if __name__ == '__main__':
    n = int(input())
    for i in range(n):
        print(i*i)


 5


0
1
4
9
16


## Write a function

In [1]:
def is_leap(year):
    leap = False
    
    if(year%400==0):
        leap=True
    elif(year%100==0):
        leap=False
    elif(year%4==0):
        leap=True
    return leap



year = int(input())
print(is_leap(year))

 1990


False


## Print Function

In [2]:
def is_consecutive(n):
    for i in range(n):
        print(i+1,end="")
n = int(input())
is_consecutive(n)


 3


123

# Data types

## List Comprehensions

In [3]:
x = int(input())
y = int(input())
z = int(input())
n = int(input())
    
amd = [[i,j,k] for i in range(x+1) for j in range(y+1) for k in range(z+1) if i+j+k!=n]
print (amd)


 1
 1
 1
 2


[[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1]]


## Find the Runner-Up Score!

In [5]:
if __name__ == '__main__':
    n = int(input())
    arr = map(int, input().split())
    print(sorted(list(set(arr)))[-2])


 5
 2 3 6 6 5


5


## Nested Lists

In [6]:
if __name__ == '__main__':
    student_grade=[]
    for _ in range(int(input())):
         name=input()
         score=float(input())
         student_grade.append([name,score])
    sort=sorted(list(set([x[1] for x in student_grade])))
    second=sort[1]
    
    student_list=[]
    for n in student_grade:
        if second==n[1]:
            student_list.append(n[0])
    for n in sorted(student_list):
        print(n)


 5
 Harry
 37.21
 Berry
 37.21
 Tina
 37.2
 Akriti
 41
 Harsh
 39


Berry
Harry


## Finding the percentage

In [7]:
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()
    l=list(student_marks[query_name])
    print("%0.2f" %(sum(l)/(len(l))))


 3 
 Krishna 67 68 69 
 Arjun 70 98 63
  Malika 52 56 60 
 Malika


56.00


## Lists

In [8]:
if __name__ == '__main__':
    N = int(input())
    List=list()
    for i in range(N):
       name,*a=input().split()
       b=list(map(int,a))
       if len(b)==2:
          f=[b[0]]
          s=[b[1]]
       elif len(b)==1:
          f=[b[0]]
       if name =='insert':
          List.insert(f[0],s[0])
       elif name == 'append':
          List.append(f[0])
       elif  name == 'remove':
          List.remove(f[0])
       elif name =='print':
          print(List)
       elif name == 'reverse':
          List.reverse()
       elif name =='pop':
          List.pop()
       elif name == 'sort':
          List.sort()


 12 
 insert 0 5 
 insert 1 10 
 insert 0 6 
 print


[6, 5, 10]


  remove 6 
 append 9 
 append 1 
 sort 
 print 


[1, 5, 9, 10]


 pop 
 reverse 
 print


[9, 5, 1]


## Tuples

In [11]:
if __name__ == '__main__':
    n = int(input())
    integer_list = map(int, input().split())
    t=tuple(integer_list)
    print(hash(t))


 2
 1 2


-3550055125485641917


# STRINGS

## sWAP cASE

In [1]:
def swap_case(s):
    return s.swapcase()

if __name__ == '__main__':
    s = input()
    result = swap_case(s)
    print(result)

 Hello Altynay


hELLO aLTYNAY


## String Split and Join

In [4]:
def split_and_join(line):
    # write your code here
     a=line.split(" ")
     a="-".join(a)
     return a
     
if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)

 this is a string


this-is-a-string


## What's Your Name?

In [6]:
def print_full_name(first, last):
    # Write your code here
    a='Hello {} {}! You just delved into python.'.format(first,last)
    print(a)
if __name__ == '__main__':
    first_name = input()
    last_name = input()
    print_full_name(first_name, last_name)

 Ross
 Taylor


Hello Ross Taylor! You just delved into python.


## Mutations

In [8]:
def mutate_string(string, position, character):
    l=list(string)
    l[position]=character
    string=''.join(l)
    return string

if __name__ == '__main__':
    s = input()
    i, c = input().split()
    s_new = mutate_string(s, int(i), c)
    print(s_new)

 abracadabra
 5 k


abrackdabra


## Find a string

In [9]:
def count_substring(string, sub_string):
    count = 0
    for i in range(len(string)-len(sub_string)+1):
        if (string[i:i+len(sub_string)] == sub_string):
            count += 1
    return count
    

if __name__ == '__main__':
    string = input().strip()
    sub_string = input().strip()
    
    count = count_substring(string, sub_string)
    print(count)

 ABCDCDC
 CDC


2


## String Validators

In [10]:
if __name__ == '__main__':

    string = input()
print(any(char.isalnum() for char in string))
print(any(char.isalpha() for char in string))
print(any(char.isdigit() for char in string))
print(any(char.islower() for char in string))
print(any(char.isupper() for char in string))


 qA2


True
True
True
True
True


## Text Alignment

In [11]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
input_ = int(input()) # This must be an odd number
c = 'H'

for i in range(input_):
    print((c*i).rjust(input_-1)+c+(c*i).ljust(input_-1))

for i in range(input_+1):
    print((c*input_).center(input_*2)+(c*input_).center(input_*6))

for i in range((input_+1)//2):
    print((c*input_*5).center(input_*6))

for i in range(input_+1):
    print((c*input_).center(input_*2)+(c*input_).center(input_*6))

for i in range(input_):
    print(((c*(input_-i-1)).rjust(input_)+c+(c*(input_-i-1)).ljust(input_)).rjust(input_*6))


 5


    H    
   HHH   
  HHHHH  
 HHHHHHH 
HHHHHHHHH
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
                    HHHHHHHHH 
                     HHHHHHH  
                      HHHHH   
                       HHH    
                        H     


## Text Wrap

In [14]:
import textwrap

def wrap(string, max_width):
    return textwrap.fill(string, max_width)
if __name__ == '__main__':
    string, max_width = input(), int(input())
    result = wrap(string, max_width)
    print(result)

 ABCDEFGHIJKLIMNOQRSTUVWXYZ
 4


ABCD
EFGH
IJKL
IMNO
QRST
UVWX
YZ


## Designer Door Mat

In [15]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
N, M = map(int, input().split())
for i in range(1, N, 2):
    print(str('.|.' * i).center(M, '-'))
print('WELCOME'.center(M, '-'))
for i in range(N-2, -1, -2):
    print(str('.|.' * i).center(M, '-'))


 9 27


------------.|.------------
---------.|..|..|.---------
------.|..|..|..|..|.------
---.|..|..|..|..|..|..|.---
----------WELCOME----------
---.|..|..|..|..|..|..|.---
------.|..|..|..|..|.------
---------.|..|..|.---------
------------.|.------------


## String Formatting

In [16]:
def print_formatted(number):
    # your code goes here
    width = len("{0:b}".format(number))

    for i in range(1, number + 1):
        print("{0:{w}d} {0:{w}o} {0:{w}X} {0:{w}b}".format(i, w = width))
if __name__ == '__main__':
    n = int(input())
    print_formatted(n)

 17


    1     1     1     1
    2     2     2    10
    3     3     3    11
    4     4     4   100
    5     5     5   101
    6     6     6   110
    7     7     7   111
    8    10     8  1000
    9    11     9  1001
   10    12     A  1010
   11    13     B  1011
   12    14     C  1100
   13    15     D  1101
   14    16     E  1110
   15    17     F  1111
   16    20    10 10000
   17    21    11 10001


## Alphabet Rangoli

In [17]:
def print_rangoli(size):
    # your code goes here
    import string
    alpha = string.ascii_lowercase

    L = []
    for i in range(n):
        s = "-".join(alpha[i:n])
        L.append((s[::-1]+s[1:]).center(4*n-3, "-"))
        
    print('\n'.join(L[:0:-1]+L))
if __name__ == '__main__':
    n = int(input())
    print_rangoli(n)

 5


--------e--------
------e-d-e------
----e-d-c-d-e----
--e-d-c-b-c-d-e--
e-d-c-b-a-b-c-d-e
--e-d-c-b-c-d-e--
----e-d-c-d-e----
------e-d-e------
--------e--------


## Capitalize!

In [ ]:
import math
import os
import random
import re
import sys

def solve(s):
    for i in s.split():
        s = s.replace(i,i.capitalize())
    return s

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w'
    s = input()
    result = solve(s)
    fptr.write(result + '\n')
    fptr.close()

## The Minion Game

In [ ]:
    def minion_game(string):
    # your code goes here
    Kevin = 0;
    Stuart = 0;
    str_len = len(string)
    for i in range(str_len):
        if string[i] in "AEIOUaeiou":
            Kevin += (str_len)-i
        else :
            Stuart += (str_len)-i
    
    if  Kevin > Stuart:
        print("Kevin {}".format(Kevin))
    elif  Kevin < Stuart:
        print("Stuart {}".format(Stuart))
    elif Kevin == Stuart:
        print("Draw")
    else :
        print("Draw") 
if __name__ == '__main__':

## Merge the Tools!

In [ ]:
def merge_the_tools(string, k):
    # your code goes here
    for i in range(0,len(string), k):
        line = string[i:i+k]
        new = ""
        for i in line:
            if i not in new:
                new+=i
        print(new)
if __name__ == '__main__':
    string, k = raw_input(), int(raw_input())
    merge_the_tools(string, k)

# Sets

## Introduction to Sets

In [ ]:
from __future__ import division

def average(array):
    # your code goes here
    sum_=sum(set(array))
    len_=len(set(array))
    avg=sum_/len_
    return avg
if __name__ == '__main__':
    n = int(input())
    arr = map(int, input().split())
    result = average(arr)
    print(result)

## No Idea!

In [ ]:
n_m = raw_input().split()
n_m = map(int, n_m)
n = map(int, raw_input().split())
A = set(map(int, raw_input().split()))
B = set(map(int, raw_input().split()))

counter = 0
for i in n:
    if i in A:
        counter += 1
    elif i in B:
        counter -= 1

print counter


## Symmetric Difference

In [ ]:
a=int(raw_input())
a2=set(map(int,raw_input().split()))
b=int(raw_input())
b2=set(map(int,raw_input().split()))

adif=a2.difference(b2)
bdif=b2.difference(a2)

newout=adif.union(bdif)
 
for i in sorted(list(newout)):
    print(i)


## Set .add()

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
N=int(raw_input())
set_=set(raw_input() for i in range(N))
print(len(set_))


## Set .union() Operation

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
n=int(raw_input())
set1=set(map(int,raw_input().split()))
n2=int(raw_input())
set2=set(map(int,raw_input().split()))
newset=set1.union(set2)
print(len(newset))


## Set .intersection() Operation

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
n=int(raw_input())
set1=set(map(int,raw_input().split()))
n2=int(raw_input())
set2=set(map(int,raw_input().split()))
newset=set1.intersection(set2)
print(len(newset))


## Set .difference() Operation

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
n=int(raw_input())
set1=set(map(int,raw_input().split()))
n2=int(raw_input())
set2=set(map(int,raw_input().split()))
newset=set1.difference(set2)
print(len(newset))


## Set .symmetric_difference() Operation

In [ ]:
eng_num = int(raw_input())
eng_set = set(map(int, raw_input().split()))
fren_num = int(raw_input())
fren_set = set(map(int, raw_input().split()))

print len(eng_set.difference(fren_set))

## Set Mutations

In [ ]:
len_set = int(input())

storage = set(map(int, input().split()))

op_len = int(input())

for i in range(op_len):
    operation = input().split()
    if operation[0] == 'intersection_update':
        temp_storage = set(map(int, input().split()))
        storage.intersection_update(temp_storage)
    elif operation[0] == 'update':
        temp_storage = set(map(int, input().split()))
        storage.update(temp_storage)
    elif operation[0] == 'symmetric_difference_update':
        temp_storage = set(map(int, input().split()))
        storage.symmetric_difference_update(temp_storage)
    elif operation[0] == 'difference_update':
        temp_storage = set(map(int, input().split()))
        storage.difference_update(temp_storage)
    else :
        assert False

print(sum(storage))

## The Captain's Room

In [ ]:

N = int(input())

storage = map(int, input().split())
storage = sorted(storage)

for i in range(len(storage)):
    if(i != len(storage)-1):
        if(storage[i]!=storage[i-1] and storage[i]!=storage[i+1]):
            print(storage[i])
            break;
    else:
        print(storage[i])

## Check Subset

In [ ]:
T = int(input())

for _ in range(T):
    a = input()
    A = set(input().split())
    b = int(input())
    B = set(input().split())
    print(A.issubset(B))

## Check Strict Superset

In [ ]:
storage = set(input().split())
N = int(input())
output = True

for i in range(N):
    storage2 = set(input().split())
    if not storage2.issubset(storage):
        output = False
    if len(storage2) >= len(storage):
        output = False

print(output)

# Collections

## collections.Counter()

In [7]:
from collections import Counter
X = int(input())
N = map(int,input().split())
x = int(input())
L = map(tuple,(map(int,input().split()) for _ in range(x)))
n = Counter(N)
p =0
for i in L:
    if i[0] in n.keys() and n[i[0]] >0 :
        n[i[0]] = n[i[0]]-1
        p = p+i[1]
          
print(p)

 10
 2 3 4 5 6 8 7 6 5 18
 6
 6 55
 6 45
 6 55
 4 40
 18 60
 10 50


200


## DefaultDict Tutorial

In [9]:
from collections import defaultdict
defdict = defaultdict(list)
list1=[]

a,b = map(int,input().split())

for i in range(a):
    defdict[input()].append(i+1) 

for i in range(b):
    list1=list1+[input()]  

for i in list1: 
    if i in defdict:
        print(" ".join( map(str,defdict[i]) ))
    else:
        print(-1)


 5 2
 a
 a
 b
 a
 b
 a
 b


1 2 4
3 5


## Collections.namedtuple()

In [11]:
import collections

n = int(input())
scol = ','.join(input().split())
Student = collections.namedtuple('Student',scol)

sum = 0
for i in range(n):
    row = input().split()
    student = Student(*row)
    sum += int(student.MARKS)

print(sum/n)


 5
 ID         MARKS      NAME       CLASS
 1          97         Raymond    7    
 2          50         Steven     4 
 3          91         Adrian     9 
 4          72         Stewart    5         
 5          80         Peter      6   


78.0


## Collections.OrderedDict()

In [12]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from collections import OrderedDict
n, d = int(input()), OrderedDict()
for _ in range(n):
    line = input().rstrip().split()
    item_name, net_price = ' '.join(line[:-1]), int(line[-1])
    if item_name in d: d[item_name] += net_price
    else: d[item_name] = net_price

for item in sorted(sorted(d, key=lambda t: t[0])):
    print(item, d[item])
                    

 9
 BANANA FRIES 12
 POTATO CHIPS 30
 APPLE JUICE 10
 CANDY 5
 APPLE JUICE 10
 CANDY 5
 CANDY 5
 CANDY 5
 POTATO CHIPS 30


APPLE JUICE 20
BANANA FRIES 12
CANDY 20
POTATO CHIPS 60


## Word Order

In [13]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
number = int(input())
counter = {}
words = []

for i in range(number):
  word = input()
  words.append(word)
  if word in counter:
    counter[word] += 1
  else:
    counter[word] = 1
    
print(len(counter))
print(' '.join([str(counter[word]) for word in counter]))


 4
 bcdef
 abcdefg
 bcde
 bcdef


3
2 1 1


## DefaultDict Tutorial

In [1]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from collections import defaultdict
defdict = defaultdict(list)
list1=[]

a,b = map(int,input().split())

for i in range(a):
    defdict[input()].append(i+1) 

for i in range(b):
    list1=list1+[input()]  

for i in list1: 
    if i in defdict:
        print (" ".join( map(str,defdict[i]) ))
    else:
        print(-1)

 5 2
 a
 a
 b
 a
 b
 a
 b


1 2 4
3 5


## Collections.deque()

In [2]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from collections import deque
number = int(input())
table = deque()
for _ in range(number):
    lst = list(input().split())
    if lst[0]=='append':
        table.append(int(lst[1]))
    elif lst[0]=='appendleft':
        table.appendleft(int(lst[1]))
    elif lst[0]=='popleft':
        table.popleft()
    elif lst[0]=='pop':
        table.pop()
for i in table:
    print(i,end=' ')


 6
 append 1
 append 2
 append 3
 appendleft 4
 pop
 popleft


1 2 

## Piling Up!

In [3]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from collections import deque

N = int(input())

for _ in range(N):
    True_ = True
    input()
    deq = deque(map(int, input().strip().split()))
    if(deq[0] >= deq[-1]):
        max = deq.popleft()
    else:
        max = deq.pop()
    while deq:
        if(len(deq)==1):
            if(deq[0] <= max):
                break
            else:
                True_ = False
                break
        else:
            if(deq[0]<=max and deq[-1]<=max):
                if(deq[0]>=deq[-1]):
                    max = deq.popleft()
                else:
                    max = deq.pop()
            elif(deq[0]<=max):
                max = deq.popleft()
            elif(deq[-1]<=max):
                max = deq.pop()
            else:
                True_ = False
                break
    if True_:
        print("Yes")
    else:
        print("No")


 2
 6
 4 3 2 1 3 4


Yes


 3
 1 2 3


Yes


## Calendar Module

In [4]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import datetime
import calendar

m, d, y = map(int, input().split())
Date = datetime.date(y, m, d)
print(calendar.day_name[Date.weekday()].upper())


 08 05 2015


WEDNESDAY


## Built-Ins
## Athlete Sort

In [6]:
#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    k = int(input())


 5 3
 10 2 5
 7 1 0
 9 9 9
 1 23 12
 6 5 9
 1


## Decorators 2 - Name Directory
## Closures and Decorations

In [ ]:
import operator

def person_lister(f):
    def inner(people):
        # complete the function
    return inner

@person_lister
def name_format(person):
    return ("Mr. " if person[3] == "M" else "Ms. ") + person[0] + " " + person[1]

if __name__ == '__main__':
    people = [input().split() for i in range(int(input()))]
    print(*name_format(people), sep='\n')

## Numpy
## Arrays

In [1]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    arr.reverse()
    numpy_arr = numpy.array(arr,float)
    return numpy_arr

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

 1 2 3 4 -8 -10


[-10.  -8.   4.   3.   2.   1.]


## Shape and Reshape

In [3]:
import numpy 
arr=numpy.array(input().strip().split(' '),dtype='int')
new_arr=numpy.reshape(arr,(3,3))
print(new_arr)

 1 2 3 4 5 6 7 8 9


[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Transpose and Flatten

In [4]:
import numpy
n, m = map(int, input().split())

storage = numpy.array([input().strip().split() for _ in range(n)], int)
print (storage.transpose())
print (storage.flatten())

 2 2
 1 2
 3 4


[[1 3]
 [2 4]]
[1 2 3 4]


## Concatenate

In [3]:
import numpy as np
a, b, c = map(int,input().split())
arrA = np.array([input().split() for _ in range(a)],int)
arrB = np.array([input().split() for _ in range(b)],int)
print(np.concatenate((arrA, arrB), axis = 0))

 4 3 2
 1 2
 1 2
 1 2
 1 2
 3 4
 3 4
 3 4


[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


## Zeros and Ones

In [4]:
import numpy
N = tuple(map(int, input().split()))
print(numpy.zeros(N, int))
print(numpy.ones(N, int))

 3 3 3


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


## Eye and Identity

In [5]:
import numpy
numpy.set_printoptions(sign=' ')
a,b=map(int, input().split())
print(numpy.array(numpy.eye(a,b),dtype=float))

 3 3


[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Array Mathematics

In [6]:
import numpy

N, M = map(int, input().split())

A = numpy.array([list(map(int, input().split())) for n in range(N)])
B = numpy.array([list(map(int, input().split())) for n in range(N)])

print(A + B)
print(A - B)
print(A * B)
print(A // B)
print(A % B)
print(A ** B)


 1 4
 1 2 3 4
 5 6 7 8


[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


## Floor, Ceil and Rint

In [7]:
import numpy

numpy.set_printoptions(sign=' ')

array = numpy.array(input().split(),float)

print(numpy.floor(array))
print(numpy.ceil(array))
print(numpy.rint(array))

 1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9


[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


## Sum and Prod

In [9]:
import numpy

N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)], int)
print(numpy.prod(numpy.sum(A, axis=0), axis=0))

 2 2
 1 2
 3 4


24


## Min and Max

In [ ]:
import numpy

N, M = map(int, input().split())

my_array = numpy.array([ map(int, input().split()) for i in range(N) ])

print(numpy.max(numpy.min(my_array, axis = 1)))

## Mean, Var, and Std

In [ ]:
import numpy

a = map(int, input().split())
b = numpy.array([input().split() for i in range(a[0])], int)
print(numpy.mean(b, axis = 1))
print(numpy.var(b, axis = 0))
print(numpy.std(b, axis = None))

## Dot and Cross

In [ ]:
import numpy

N = int(input())
A = numpy.array([input().split() for i in range(N)], int)
B = numpy.array([input().split() for i in range(N)], int)
print numpy.dot(A, B)

## Inner and Outer

In [ ]:

import numpy

A = numpy.array(input().split(), int)
B = numpy.array(input().split(), int)

print numpy.inner(A, B)
print numpy.outer(A, B)

## Polynomials

In [ ]:
import numpy
k = numpy.array(map(float,input().split()))
p = input()
print numpy.polyval(k,p)

## Linear Algebra

In [ ]:
import numpy as np
N = int(input())
A = np.array([input().split() for i in range(N)],float)
print(np.linalg.det(A))

# Problem 2
## Birthday Cake Candles



In [ ]:
import math
import os
import random
import re
import sys

# Complete the birthdayCakeCandles function below.
def birthdayCakeCandles(ar):

    ar.sort()

    result = ar.count(ar[len(ar)-1])
    return result


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    ar_count = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = birthdayCakeCandles(ar)

    fptr.write(str(result) + '\n')

    fptr.close()

## Number Line Jumps


In [ ]:
import math
import os
import random
import re
import sys

# Complete the kangaroo function below.
def kangaroo(x1, v1, x2, v2):
    
    if x2 > x1 and v2 > v1:
        return "NO"
    else:
        if v2-v1 == 0:
            return 'NO'
        else:
            result = (x1-x2) % (v2-v1)
            if result == 0:
                return 'YES'
            else:
                return 'NO'


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    x1V1X2V2 = input().split()

    x1 = int(x1V1X2V2[0])

    v1 = int(x1V1X2V2[1])

    x2 = int(x1V1X2V2[2])

    v2 = int(x1V1X2V2[3])

    result = kangaroo(x1, v1, x2, v2)

    fptr.write(result + '\n')

    fptr.close()

## Viral Advertising



In [ ]:
#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'viralAdvertising' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER n as parameter.
#

def viralAdvertising(n):
    numOfPeopleAdvertised=5
    
    totNumOfPeopleLiked = 0
    for day in range(n):
        numOfPeopleLiked = numOfPeopleAdvertised//2
        totNumOfPeopleLiked += numOfPeopleLiked
        numOfPeopleAdvertised = numOfPeopleLiked*3
        
        
    return totNumOfPeopleLiked

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    result = viralAdvertising(n)

    fptr.write(str(result) + '\n')

    fptr.close()


## Recursive Digit Sum

In [ ]:
#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'superDigit' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. STRING n
#  2. INTEGER k
#

def superDigit(n, k):
     digits = map(int, list(n))
     return get_super_digit(str(sum(digits) * k))

def get_super_digit(p):
    if len(p) == 1:
        return int(p)
    else:
        digits = map(int, list(p))
        return get_super_digit(str(sum(digits)))


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = first_multiple_input[0]

    k = int(first_multiple_input[1])

    result = superDigit(n, k)

    fptr.write(str(result) + '\n')

    fptr.close()


## Insertion Sort - Part 1

In [ ]:

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    target = arr[-1]
    idx = n-2

    while (target < arr[idx]) and (idx >= 0):
        arr[idx+1] = arr[idx]
        print(*arr)
        idx -= 1

    arr[idx+1] = target
    print(*arr)

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)

## Insertion Sort - Part 2



In [8]:
import sys

def insertionSort1(start, arr):
    probe = arr[start]
    
    for ind in range(start-1, -1, -1):
        if arr[ind] > probe:
            arr[ind+1] = arr[ind]
        else:
            arr[ind+1] = probe
            break
    if arr[0] > probe:
        arr[0] = probe

def insertionSort2(n, arr):
    for ind in range(1, len(arr)):
        insertionSort1(ind, arr)
        print(" ".join(map(str, arr)))

if __name__ == "__main__":
    n = int(input().strip())
    arr = list(map(int, input().strip().split(' ')))
    insertionSort2(n, arr)

 6
 1 4 3 5 6 2 


1 4 3 5 6 2
1 3 4 5 6 2
1 3 4 5 6 2
1 3 4 5 6 2
1 2 3 4 5 6
